chef/chef-foundation

- .github/CODEOWNERS
> updating code owners

- .expeditor/adhoc-canary.omnibus.yml
- .expeditor/release.omnibus.yml
- Gemfile.lock
A new platform called Rocky Linux has emerged out of CentOS. 
Add RockyLinux-8 Builder and tester
> Add RockyLinux-8 builder & Tester

- .expeditor/adhoc-canary.omnibus.yml
- .expeditor/release.omnibus.yml
> Added rockylinux-9 to chef-foundation

- Gemfile.lock
- config/projects/chef-foundation.rb
> updated gemfile lock omnibus version to 9.0.23

- .expeditor/adhoc-canary.omnibus.yml
- .expeditor/release.omnibus.yml
> Support Rocky-arm-8/9

- .expeditor/config.yml
creating the 2-stable agent for chef-17 chef-foundation.
> adding 2-stable back

- CONTRIBUTING.md
- README.md
updating contribution how to. 
we want people to be able to add PR's and get their changes in.
> adding contribution how to

- Gemfile.lock
- config/projects/chef-foundation.rb
> updated the gemfile lock

- .expeditor/config.yml
- .expeditor/release.omnibus.yml
- Gemfile
- Gemfile.lock
- config/projects/chef-foundation.rb
- omnibus_overrides.rb
- Support Rocky Platform
- Pick omnibus s/w  from main
- Unpin dependedncies (libxslt & libxml)
- Update gems
- Fix windows pkg signing  issue
- Sync omnibus-overides.rb with chef-17 dependencies
> Chef-17 Migration

- README.md
> testing version bump

- .expeditor/adhoc-canary.omnibus.yml
- .expeditor/release.omnibus.yml
Adding new platform amazon 2023 to builder and tester in order to bring up new platform.
> added amazon2023 builder and tester

- Gemfile.lock
Updates through `bundle update --conservative omnibus`
```
❯ bundle update --conservative omnibus
Fetching https://github.com/chef/omnibus.git
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies.........
Using rake 13.1.0
Using public_suffix 5.0.1
Using artifactory 3.0.15
Using ast 2.4.2
Using awesome_print 1.9.2
Using libyajl2 2.1.0
Using aws-partitions 1.710.0
Using jmespath 1.6.2
Using mixlib-log 3.0.9
Using rack 2.2.6.2
Using bcrypt_pbkdf 1.1.0
Using uuidtools 2.2.0
Using concurrent-ruby 1.2.0
Using fuzzyurl 0.9.0
Using tomlrb 1.3.0
Using ruby2_keywords 0.0.5
Using tty-color 0.6.0
Using strings-ansi 0.2.0
Using unicode-display_width 2.4.2
Using unicode_utils 1.4.0
Using tty-cursor 0.7.1
Using tty-screen 0.8.1
Using wisper 2.0.1
Using method_source 1.0.0 …
```
> 9.0.24 omnibus bump for Solaris pkgmogrify changes

- omnibus_overrides.rb
> To fix signature issue on Notarization

- .expeditor/release.omnibus.yml
> Update Windows builder matching Infra-client  platforms

- .expeditor/adhoc-canary.omnibus.yml
- .expeditor/release.omnibus.yml
Since we have a condition here to skip artifactory platforms for freebsd13 , this platform's artifacts are not being pushed to artifactory. so removing the condition here.
> build freebsd-13 artifacts

- Gemfile.lock
this change will pick latest sha of omnibus-software
> updated latest sha of omnibus-software

- omnibus-test.ps1
> Fix through -> threw

- .expeditor/adhoc-canary.omnibus.yml
- .expeditor/release.omnibus.yml
We have removed win-10 from the pipeline temporarily earlier in this pr, because there was some issue while picking up the agent at that time. https://github.com/chef/chef-foundation/pull/112/files#diff-d8f23560e38d3c6fdb8b0e9941eda7d9b22c958c97eaa77897a64d754fbd9a6cL99 
Now adding it back to the pipeline.
> re-add win10 platform to the pipeline

- .expeditor/adhoc-canary.omnibus.yml
- .expeditor/release.omnibus.yml
This PR modifies the pipeline configuration to include support for macOS 13 and 14 ARM architectures
> Update pipeline to support macOS 13 and 14 ARM 

- omnibus.rb
These changes ensure that Omnibus can fetch remote assets securely and reliably, resolving NetFetcher errors related to S3 credentials and source access during the build of chef-foundation.
This PR is essential for successful builds in environments that require authenticated asset retrieval and internal source usage.
Log : https://buildkite.com/chef/chef-chef-foundation-main-omnibus-release/builds/217#01975475-d904-4305-8525-5fbe1f79fc89
> Fix NetFetcher Error

- README.md
> Test Version Bump
